version: "3.8"

services:
  server:
    build: .
    image: ghcr.io/qrlk/locator:master
    ports:
      - 46547:46547
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '10'
      driver: json-file